-- Tabla de Usuarios
CREATE TABLE Usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    correo_electronico VARCHAR2(255) UNIQUE NOT NULL,
    contraseña VARCHAR2(255) NOT NULL,
    rol VARCHAR2(50) CHECK (rol IN ('Administrador', 'Auxiliar de Registro')) NOT NULL
);

-- Tabla de Comerciantes
CREATE TABLE Comerciantes (
    id_comerciante NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_razon_social VARCHAR2(255) NOT NULL,
    municipio VARCHAR2(100) NOT NULL,
    telefono VARCHAR2(20), -- Campo opcional
    correo_electronico VARCHAR2(255), -- Campo opcional
    fecha_registro DATE DEFAULT SYSDATE NOT NULL, -- Estaba faltando
    estado VARCHAR2(20) CHECK (estado IN ('Activo', 'Inactivo')) NOT NULL,
    fecha_actualizacion DATE DEFAULT SYSDATE NOT NULL,
    usuario_actualizacion VARCHAR2(50) -- Se mantiene como campo informativo
);

-- Tabla de Establecimientos
CREATE TABLE Establecimientos (
    id_establecimiento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL,
    ingresos NUMBER(15,2) NOT NULL, -- Permite valores con dos decimales
    numero_empleados NUMBER NOT NULL, -- Se corrigió el nombre
    id_comerciante NUMBER NOT NULL,
    fecha_actualizacion DATE DEFAULT SYSDATE NOT NULL,
    usuario_actualizacion VARCHAR2(50),
    CONSTRAINT fk_establecimiento_comerciante FOREIGN KEY (id_comerciante) REFERENCES Comerciantes(id_comerciante)
);
